name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: |
          make jdk
          make
          mv vizlink/target/vizlink vizlink-darwin-arm64
      - uses: softprops/action-gh-release@v2
        with:
          files: vizlink-darwin-arm64

  release-amd64:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v3
      - run: |
          make jdk-amd64
          make
          mv vizlink/target/vizlink vizlink-darwin-amd64
      - uses: softprops/action-gh-release@v2
        with:
          files: vizlink-darwin-amd64
