name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: |
          make jdk
          make
          mv vizlink/target/vizlink vizlink-darwin-arm64
      - uses: softprops/action-gh-release@v2
        with:
          files: vizlink-darwin-arm64
