name: CD

on:
  pull_request: # FIXME: `push` before merging
    branches: ["main"]

jobs:
  release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: |
          make jdk
          make
      - uses: softprops/action-gh-release@v2
        with:
          files: vizlink/target/vizlink
