name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: |
          make jdk
          make
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          make jdk-windows-amd64
          [System.Environment]::SetEnvironmentVariable("JAVA_HOME", "$pwd\bellsoft-liberica-vm-core-openjdk21-23.1.2")
          [System.Environment]::SetEnvironmentVariable("Path", [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine) + ";$pwd\apache-maven-3.9.7\bin")
          mvn install -f vizlink/pom.xml -q
          mvn package -f vizlink/pom.xml -q -Pnative -DskipTests

