name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-latest-large, windows-latest, ubuntu-latest]
        arch: [darwin-arm64, darwin-amd64, windows-amd64, ubuntu-amd64]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          cache: "maven"
          distribution: "liberica"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: "21"
          native-image-job-reports: "true"

      - run: |
          mvn install -f vizlink/pom.xml -q
          mvn package -f vizlink/pom.xml -q -Pnative -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: vizlink-${{ matrix.arch }}
          path: |
            vizlink/target/vizlink
            vizlink/target/vizlink.exe
            vizlink/target/*.dll
            vizlink/target/*.so
