name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: HelloWorld on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-latest-large, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          cache: "maven"
          distribution: "liberica"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: "21"
          native-image-job-reports: "true"

      - name: build vizlink
        run: |
          mvn install -f vizlink/pom.xml -q
          mvn package -f vizlink/pom.xml -q -Pnative -DskipTests

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: vizlink-${{ matrix.os }}
          path: vizlink/target/*
