name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    name: ${{ matrix.os.arch }}
    runs-on: ${{ matrix.os.image }}
    strategy:
      matrix:
        os:
          - arch: darwin-arm64
            image: macos-latest
            zip: zip -j vizlink-darwin-arm64.zip vizlink/target/vizlink
          - arch: darwin-amd64
            image: macos-latest-large
            zip: zip -j vizlink-darwin-amd64.zip vizlink/target/vizlink
          - arch: windows-amd64
            image: windows-latest
            zip: Compress-Archive -Destination vizlink-windows-amd64.zip -Path vizlink/target/vizlink.exe, vizlink/target/*.dll
          - arch: linux-amd64
            image: ubuntu-latest
            zip: zip -j vizlink-linux-amd64.zip vizlink/target/vizlink vizlink/target/*.so

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          cache: "maven"
          distribution: "liberica"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: "21"
          native-image-job-reports: "true"

      - run: |
          mvn install -f vizlink/pom.xml -q
          mvn package -f vizlink/pom.xml -q -Pnative -DskipTests

      - run: ${{ matrix.os.zip }}

      - uses: actions/upload-artifact@v4
        with:
          name: vizlink-${{ matrix.os.arch }}
          path: vizlink-${{ matrix.os.arch }}.zip

      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: vizlink-${{ matrix.os.arch }}.zip
